name: Restrict Merge to Main from feature branch
on:
  pull_request:
    branches:
      - main
jobs:
  restrict_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check Source Branch
        if: "!startsWith(github.event.pull_request.head.ref, 'feature/')"
        run: |
          echo "Pull requests to main must come from feature/* branch."
          exit 1
